export const IPC = {
  FILE_READ: 'file:read',
  FILE_WRITE: 'file:write',
  FILE_CREATE: 'file:create',
  FILE_READ_DIR_TREE: 'file:readDirTree',

  DIALOG_OPEN_FOLDER: 'dialog:openFolder',
  DIALOG_OPEN_FILE: 'dialog:openFile',
  DIALOG_SAVE_FILE: 'dialog:saveFile',

  TERMINAL_SPAWN: 'terminal:spawn',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_DISPOSE: 'terminal:dispose',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',

  WATCHER_CHANGE: 'watcher:change',

  PROJECTS_GET_RECENT: 'projects:getRecent',
  PROJECTS_ADD_RECENT: 'projects:addRecent',
  PROJECTS_REMOVE_RECENT: 'projects:removeRecent',
  PROJECTS_GET_DEFAULT_PATH: 'projects:getDefaultPath',

  ROSE_CHECK_MD: 'rose:checkMd',
  ROSE_INIT_PROJECT: 'rose:initProject',

  HEARTBEAT_RUN: 'heartbeat:run',
  HEARTBEAT_GET_LOGS: 'heartbeat:getLogs',
  HEARTBEAT_LOG_CONTENT: 'heartbeat:logContent',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',

  HEALTH_CHECK_ALL: 'health:checkAll',

  WHISPER_TRANSCRIBE: 'whisper:transcribe',

  INDEXING_PROJECT: 'indexing:project',
  INDEXING_PROGRESS: 'indexing:progress',

  AI_CHAT: 'ai:chat',
  AI_COMPRESS: 'ai:compress',
  AI_MODEL_SELECTED: 'ai:modelSelected',
  AI_STREAM_RESET: 'ai:streamReset',
  AI_FILE_MODIFIED: 'ai:fileModified',
  AI_TOOL_CALL_START: 'ai:toolCallStart',
  AI_TOOL_CALL_END: 'ai:toolCallEnd',
  AI_THINKING: 'ai:thinking',
  AI_TOKEN: 'ai:token',

  LSP_PY_TO_SERVER: 'lsp:py:toServer',
  LSP_PY_FROM_SERVER: 'lsp:py:fromServer',
  LSP_TS_TO_SERVER: 'lsp:ts:toServer',
  LSP_TS_FROM_SERVER: 'lsp:ts:fromServer',
  LSP_STARTED: 'lsp:started',
  LSP_STOPPED: 'lsp:stopped',

  // Docker view
  DOCKER_CHECK: 'docker:check',
  DOCKER_LIST_COMPOSE: 'docker:listCompose',
  DOCKER_PS: 'docker:ps',
  DOCKER_INSPECT: 'docker:inspect',
  DOCKER_START: 'docker:start',
  DOCKER_STOP: 'docker:stop',
  DOCKER_RESTART: 'docker:restart',
  DOCKER_LOGS_SUBSCRIBE: 'docker:logsSubscribe',
  DOCKER_LOGS_UNSUBSCRIBE: 'docker:logsUnsubscribe',
  DOCKER_LOGS_DATA: 'docker:logsData',
  DOCKER_LOGS_EXIT: 'docker:logsExit',
  DOCKER_LIST_FILES: 'docker:listFiles',
  DOCKER_MOUNTS: 'docker:mounts',

  // Git view
  GIT_IS_REPO: 'git:isRepo',
  GIT_STATUS: 'git:status',
  GIT_LOG: 'git:log',
  GIT_SHOW: 'git:show',
  GIT_DIFF_FILE: 'git:diffFile',
  GIT_DIFF_WORKING: 'git:diffWorking',
  GIT_BRANCHES: 'git:branches',
  GIT_CHECKOUT: 'git:checkout',
  GIT_BRANCH_CREATE: 'git:branchCreate',
  GIT_BRANCH_DELETE: 'git:branchDelete',
  GIT_BRANCH_RENAME: 'git:branchRename',
  GIT_REMOTES: 'git:remotes',
  GIT_FETCH: 'git:fetch',
  GIT_PULL: 'git:pull',
  GIT_PUSH: 'git:push',
  GIT_STAGE: 'git:stage',
  GIT_UNSTAGE: 'git:unstage',
  GIT_DISCARD: 'git:discard',
  GIT_COMMIT: 'git:commit',
  GIT_CHERRY_PICK: 'git:cherryPick',
  GIT_REVERT: 'git:revert',
  GIT_MERGE: 'git:merge',
  GIT_REBASE: 'git:rebase',
  GIT_RESET: 'git:reset',
  GIT_TAGS: 'git:tags',
  GIT_TAG_CREATE: 'git:tagCreate',
  GIT_TAG_DELETE: 'git:tagDelete',
  GIT_STASHES: 'git:stashes',
  GIT_STASH_PUSH: 'git:stashPush',
  GIT_STASH_POP: 'git:stashPop',
  GIT_STASH_DROP: 'git:stashDrop',
  GIT_STASH_APPLY: 'git:stashApply',
  GIT_HEAD_CHANGED: 'git:headChanged',

  // Email view
  EMAIL_FETCH_MESSAGES: 'email:fetchMessages',
  EMAIL_FETCH_MESSAGE:  'email:fetchMessage',
  EMAIL_DELETE_MESSAGE: 'email:deleteMessage',
  EMAIL_TEST_CONN:      'email:testConnection',
  EMAIL_GET_FILTERS:    'email:getFilters',
  EMAIL_SET_FILTERS:    'email:setFilters',
  EMAIL_GET_META:       'email:getMeta',
  EMAIL_SET_MSG_FOLDER: 'email:setMessageFolder',

  // Chat Sessions
  SESSION_LIST: 'session:list',
  SESSION_LOAD: 'session:load',
  SESSION_SAVE: 'session:save',
  SESSION_DELETE: 'session:delete',

  // Discord view
  DISCORD_CONNECT:          'discord:connect',
  DISCORD_DISCONNECT:       'discord:disconnect',
  DISCORD_GET_CHANNELS:     'discord:getChannels',
  DISCORD_FETCH_MESSAGES:   'discord:fetchMessages',
  DISCORD_SEND_MESSAGE:     'discord:sendMessage',
  DISCORD_MESSAGE_CREATE:   'discord:messageCreate',
  DISCORD_CONNECTION_STATE: 'discord:connectionState',

  // Extensions
  EXTENSION_LIST: 'extension:list',
  EXTENSION_INSTALL: 'extension:install',
  EXTENSION_UNINSTALL: 'extension:uninstall',
  EXTENSION_ENABLE: 'extension:enable',
  EXTENSION_DISABLE: 'extension:disable',
  EXTENSION_FETCH_REGISTRY: 'extension:fetchRegistry',

  // Active Listening
  ACTIVE_LISTENING_LABEL_SPEAKER: 'activeSpeech:labelSpeaker',
  ACTIVE_LISTENING_TRAIN: 'activeSpeech:train',
  ACTIVE_LISTENING_TRAIN_STATUS: 'activeSpeech:trainStatus',
  ACTIVE_LISTENING_TRAIN_HISTORY: 'activeSpeech:trainHistory',
  ACTIVE_LISTENING_GET_SPEAKERS: 'activeSpeech:getSpeakers',
  ACTIVE_LISTENING_CREATE_SPEAKER: 'activeSpeech:createSpeaker',
  ACTIVE_LISTENING_ADD_SAMPLE: 'activeSpeech:addSample',
  ACTIVE_LISTENING_CREATE_SESSION: 'activeSpeech:createSession',
  ACTIVE_LISTENING_END_SESSION: 'activeSpeech:endSession',
  ACTIVE_LISTENING_GET_UTTERANCES: 'activeSpeech:getUtterances',
  ACTIVE_LISTENING_GET_SESSIONS: 'activeSpeech:getSessions'
} as const
